### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by sidharrth2002** [sidharrth2002/Foodeliver#1]
- [x] Change Files to Preloaded Requirements
- [x] Add Custom Queue
- [x] UI
- [x] Testing

- [x] New Class Diagram

- [x] Javadoc

- [x] Edit status in rider

- [x] How to submit java project

- [x] Removed 10 order limit
